### ISSUE TITLE
Not all pages are using the new method

### ISSUE THREAD

**Issue by Alfa-beto** [VeNoMouS/cloudflare-scrape-js2py#12] opened 2019-04-01 22:00 UTC
it's seems that not all pages are using the new method from cloudflare, some ones still using the old method, here is an example http://gnula.nu/.
I guess the solution is to maintain both, the old method and the new and select the correct, on base to the k variable.

**Comment by pro-src** [comment] 2019-04-01 22:02
Duplicate of #4

**Comment by VeNoMouS** [comment] 2019-04-02 22:50
@Alfa-beto if your using py2 try out the dev branch.

**Comment by veldjmaxis** [comment] 2019-04-03 09:56
@VeNoMouS  id dev branch @ line 167 change:
`            innerHTML = re.search(
                '<div(?: [^<>]*)? id="([^<>]*?)">([^<>]*?)<\/div>',
                body,
                re.MULTILINE | re.DOTALL
            ).group(2).replace("'", r"\'")`
to
`            innerHTML = re.search(
                '<div(?: [^<>]*)? id="([^<>]*?)">([^<>]*?)<\/div>',
                body,
                re.MULTILINE | re.DOTALL
            )

            innerHTML = innerHTML.group(2).replace("'", r"\'") if innerHTML else ""`

This will fix bug when there's no div in challenge

**Comment by VeNoMouS** [comment] 2019-04-03 12:40
wouldn't you need this in a trap since group() wouldn't be populated with index 2 if there was no regex matching?....

the expect would set it to "" ... 

just my 2 cents?

**Comment by veldjmaxis** [comment] 2019-04-03 12:47
This is same way but without using trap. If there was no regex matching first innerHTML will be set to False and next replaced by proper value.

Just a normal point of view of who prefers which solutions ;)

**Comment by veldjmaxis** [comment] 2019-04-03 13:52
Meanwhile another use case:
`var t = "service.com";
                                                        function italics (str) { return '<i>' + this + '</i>'; };
                                                        var document = {
                                                            getElementById: function () {
                                                                return {'innerHTML': '+((!+[]+true+true+true+true+true+true+true+[])+(+true)+(!+[]+true+true+true+true+true+true)+(!+[]+true+true+true+true)+(+[])+(!+[]+true+true+true)+(!+[]+true)+(!+[]+true+true+true)+(!+[]+true+true))/+((!+[]+true+true+true+[])+(!+[]+true+true+true+true+true+true+true+true)+(!+[]+true+true+true+true+true)+(!+[]+true+true)+(!+[]+true+true+true+true+true+true)+(!+[]+true+true+true+true)+(!+[]+true+true+true+true)+(!+[]+true)+(!+[]+true))'};
                                                            }
                                                        };
                                                        var s,t,o,p,b,r,e,a,k,i,n,g,f, reMYQRt={"zN":+((!+[]+true+true+true+true+true+true+true+[])+(!+[]+true+true)+(!+[]+true+true+true+true+true+true+true)+(+[])+(!+[]+true+true+true)+(+true)+(!+[]+true+true+true+true+true)+(!+[]+true+true+true)+(!+[]+true+true+true+true+true+true))/+((+true+[])+(+[])+(+[])+(!+[]+true+true)+(!+[]+true+true+true+true+true+true+true)+(!+[]+true+true+true+true)+(!+[]+true+true)+(!+[]+true)+(!+[]+true+true+true))};        ;reMYQRt.zN-=+((!+[]+true+true+true+true+true+true+true+[])+(!+[]+true+true)+(!+[]+true+true+true+true+true+true+true)+(+[])+(!+[]+true+true+true)+(+true)+(!+[]+true+true+true+true+true)+(!+[]+true+true+true)+(!+[]+true+true+true+true+true+true))/+((!+[]+true+true+true+true+true+true+[])+(!+[]+true)+(!+[]+true+true+true+true+true+true+true+true)+(!+[]+true+true+true+true+true+true)+(!+[]+true+true+true+true+true+true+true+true)+(+[])+(!+[]+true+true+true+true+true+true+true+true)+(!+[]+true+true+true+true+true+true)+(!+[]+true+true+true+true+true+true+true));reMYQRt.zN-=+((!+[]+true+true+true+true+true+true+true+true+[])+(!+[]+true+true+true)+(+true)+(+[])+(!+[]+true+true+true+true+true+true+true)+(!+[]+true+true)+(!+[]+true+true+true+true+true+true+true+true)+(!+[]+true+true+true+true+true+true+true)+(+true))/+((!+[]+true+true+true+true+true+[])+(!+[]+true+true+true)+(!+[]+true+true+true+true+true+true)+(!+[]+true+true+true+true+true)+(+[])+(!+[]+true+true+true+true+true+true+true+true)+(!+[]+true+true)+(!+[]+true+true+true+true+true+true)+(!+[]+true+true+true+true+true+true+true));reMYQRt.zN-=+((!+[]+true+true+true+true+true+true+true+[])+(!+[]+true+true)+(!+[]+true+true+true+true+true+true+true)+(+[])+(!+[]+true+true+true)+(+true)+(!+[]+true+true+true+true+true)+(!+[]+true+true+true)+(+true))/+((!+[]+true+true+true+true+true+true+true+[])+(!+[]+true+true+true+true)+(!+[]+true+true+true)+(!+[]+true+true+true+true+true+true+true+true)+(+[])+(!+[]+true+true+true)+(!+[]+true+true)+(+true)+(!+[]+true+true+true+true+true+true));reMYQRt.zN-=function(p){var p = eval(eval(atob("ZG9jdW1l")+"n"+"t"+"."+g(103)+"e"+"t"+"Element"+g(66)+"y"+"Id("+g(107)+")."+atob("aW5uZXJIVE1M"))); return +(p)}();reMYQRt.zN*=+((!+[]+true+true+true+true+true+true+true+[])+(!+[]+true+true+true+true)+(!+[]+true+true+true+true+true+true+true)+(!+[]+true+true+true+true)+(!+[]+true+true+true+true+true+true+true+true)+(!+[]+true+true+true+true+true+true+true+true)+(!+[]+true+true+true+true)+(+[])+(!+[]+true+true))/+((!+[]+true+true+true+true+true+true+[])+(!+[]+true+true+true+true+true+true)+(!+[]+true+true+true+true+true+true+true)+(!+[]+true)+(!+[]+true+true+true+true+true)+(!+[]+true+true+true+true+true+true+true+true)+(+[])+(!+[]+true+true)+(+true));reMYQRt.zN-=+((!+[]+true+true+true+true+true+true+true+true+[])+(!+[]+true+true+true)+(+true)+(+[])+(!+[]+true+true+true+true+true+true+true)+(!+[]+true+true)+(!+[]+true+true+true+true+true+true+true+true)+(!+[]+true+true+true+true+true+true+true)+(+true))/+((!+[]+true+[])+(!+[]+true+true+true+true+true)+(!+[]+true+true+true+true+true+true)+(!+[]+true+true)+(!+[]+true+true+true+true+true)+(!+[]+true+true+true+true)+(!+[]+true+true)+(!+[]+true+true+true+true+true+true+true)+(+[]));reMYQRt.zN*=+((!+[]+true+true+true+true+true+true+true+true+[])+(!+[]+true+true+true)+(+true)+(+[])+(!+[]+true+true+true+true+true+true+true)+(!+[]+true+true)+(!+[]+true+true+true+true+true+true+true+true)+(!+[]+true+true+true+true+true+true+true)+(+true))/+((!+[]+true+true+true+true+true+[])+(!+[]+true)+(!+[]+true+true+true+true+true)+(!+[]+true+true+true+true)+(+[])+(!+[]+true+true+true+true)+(+[])+(+[])+(!+[]+true+true));reMYQRt.zN+=+((!+[]+true+true+true+true+true+true+true+[])+(!+[]+true+true)+(!+[]+true+true+true+true+true+true+true)+(+[])+(!+[]+true+true+true)+(+true)+(!+[]+true+true+true+true+true)+(!+[]+true+true+true)+(!+[]+true+true+true+true+true+true))/+((!+[]+true+[])+(!+[]+true+true+true+true+true)+(!+[]+true+true+true+true)+(+true)+(+true)+(!+[]+true+true+true+true+true+true+true)+(!+[]+true+true+true+true+true)+(!+[]+true+true+true+true+true+true)+(!+[]+true));reMYQRt.zN-=+((!+[]+true+true+true+true+true+true+true+[])+(+true)+(!+[]+true+true+true+true+true+true)+(!+[]+true+true+true+true)+(+[])+(!+[]+true+true+true)+(!+[]+true)+(!+[]+true+true+true)+(!+[]+true+true))/+((!+[]+true+true+true+true+[])+(!+[]+true+true+true+true+true)+(!+[]+true+true+true+true)+(!+[]+true+true+true+true+true+true+true+true)+(!+[]+true+true)+(+[])+(!+[]+true+true+true)+(+true)+(!+[]+true+true+true+true+true+true));reMYQRt.zN+=+((!+[]+true+true+true+true+true+true+true+[])+(+true)+(!+[]+true+true+true+true+true+true)+(!+[]+true+true+true+true)+(+[])+(!+[]+true+true+true)+(!+[]+true)+(!+[]+true+true+true)+(!+[]+true+true))/(+(+((!+[]+true+true+true+true+[])+(!+[]+true+true+true+true+true+true+true)+(!+[]+true+true+true+true+true+true)+(!+[]+true+true+true+true+true+true+true)+(+[])+(!+[]+true+true+true+true+true)+(+true)+(!+[]+true+true+true+true+true+true)+(+true)))+(function(p){return eval("t"+".ch"+"a"+"r"+"C"+"o"+"d"+"e"+"A"+"t"+"("+p+")")}(+((!+[]+true+true+true+true+[])))));(+reMYQRt.zN).toFixed(10);`

With Error:
` Error Type: <class 'js2py.base.PyJsException'>
Error Contents: TypeError: 'undefined' is not a function`

**Comment by VeNoMouS** [comment] 2019-04-04 02:17
I have rolled this into the dev branch @veldjmaxis , thanks for that :)

**Comment by VeNoMouS** [comment] 2019-04-04 02:18
@Alfa-beto is this still an issue or can i close this ticket off?

**Comment by pro-src** [comment] 2019-04-05 03:56
@VeNoMouS 
https://gist.github.com/pro-src/23d77f323582ca7b964d3d78f146cb76

**Comment by Alfa-beto** [comment] 2019-04-10 14:49
close this please, sorry

**Closed** 2019-04-10 21:42 UTC
Labels: duplicate, question
