### ISSUE TITLE
CF error - RunetimError and ReferenceError

### ISSUE THREAD

**Issue by BarryThrill** [VeNoMouS/cloudflare-scrape-js2py#22] opened 2019-04-10 10:25 UTC
Hello!

So basically I was requests to post a new thread here since it is a new error.

I will start by showing the pictures:
![1](https://user-images.githubusercontent.com/15836342/55871740-9b900700-5b8b-11e9-87e7-9270d0f511a5.png)
![2](https://user-images.githubusercontent.com/15836342/55871742-9c289d80-5b8b-11e9-9fab-e32229f3367e.png)
![3](https://user-images.githubusercontent.com/15836342/55871744-9cc13400-5b8b-11e9-9e20-89d057d52470.png)

The page I am trying to requests is https://www.afew-store.com/en/ using python 3.7. I just do a normal scraper.get requests with no special headers. I do not know what really I should add as code but if someone has any suggestions on what I can post, I am happy to help as soon as possible :)

**Comment by VeNoMouS** [comment] 2019-04-10 10:27
Can you please paste the exact code your using?

**Comment by BarryThrill** [comment] 2019-04-10 10:30
Sure! Here it is:

```
connected = False
while not connected:

	try:

		url = 'https://www.afew-store.com/en/air-jordan-1-retro-high-og-turbo-green-sail-white-ltsmoke-grey/' 

		headers = {
			'Connection': 'keep-alive',
			'Cache-Control': 'no-cache',
			'Upgrade-Insecure-Requests': '1',
			'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36',
			'Accept-Language': 'sv-SE,sv;q=0.9,en-US;q=0.8,en;q=0.7,de;q=0.6',
			'origin': 'https://www.google.com'
		}

		product_info_proxies = get_random_proxy()
		r = cf_scraper.get(url, headers=headers, proxies=product_info_proxies, timeout=5)

		if r.status_code == 200:
			bs4 = soup(r.text, 'html.parser')
			connected = True

	except requests.exceptions.ProxyError:
		continue

	except Timeout:
		continue

	except Exception as err:
		randomtime = random.randint(5, 15)
		print(err)
		time.sleep(randomtime)
		continue
```

**Comment by VeNoMouS** [comment] 2019-04-10 10:42
ok... so first mistake.. 

headers should really be initialized first as a OrderedDict before you pass it...   This is because of the way __requests__ does it's __merge__ with __headers__ , i know you're py3 i know it has a really bad side effect in py2... the problem is, the header order __MATTER'S__  now with cloudflare..

can you do me a favor and , and install the dev branch 2.0.2

basiclly....

```
import cfscrape
scraper = cfscrape.create_scraper()
scraper.debug = True
scraper.get('https://www.afew-store.com/en/air-jordan-1-retro-high-og-turbo-green-sail-white-ltsmoke-grey/')
```

and email me the debug output..

**Comment by BarryThrill** [comment] 2019-04-10 10:47
> ok... so first mistake..
> 
> headers should really be initialized first as a OrderedDict before you pass it... This is because of the way **requests** does it's **merge** with **headers** , i know you're py3 i know it has a really bad side effect in py2... the problem is, the header order **MATTER'S** now with cloudflare, but thats only on the challenge... but since you are not doing any of your calls in a session, your having to challenge_solve on every single request (slow.... silly)
> 
> can you do me a favor and , and install the dev branch 2.0.2
> 
> basiclly....
> 
> ```
> import cfscrape
> scraper = cfscrape.create_scraper()
> scraper.debug = True
> scraper.get('https://www.afew-store.com/en/air-jordan-1-retro-high-og-turbo-green-sail-white-ltsmoke-grey/')
> ```
> and email me the debug output..

Im not sure if I sent to correct email, it was to venom@gen-x.co.nz - Just sent it there!

**Comment by VeNoMouS** [comment] 2019-04-10 10:49
@BarryThrill thanks for the email....

CF has changed their shit again..

**Comment by BarryThrill** [comment] 2019-04-10 10:51
> @BarryThrill thanks for the email....
> 
> CF has changed their shit again..

Oh crap, That doesn't sound good. Hopefully it is not anything serious changes :( 

Also you did inspire me abit more, What would you suggest to do to actually "speed up" my code if I might ask? 😄

**Comment by VeNoMouS** [comment] 2019-04-10 10:52
I'll help you out (prob tomorrow) after I fixed this...

**Comment by BarryThrill** [comment] 2019-04-10 10:53
> I'll help you out (prob tomorrow) after I fixed this...

Appreciate it! If I can help you out in anyway, Just comment and I will try my best to help you out for testing etc etc.

**Comment by VeNoMouS** [comment] 2019-04-10 10:54
@BarryThrill can you run that debug code once or twice more and email me in different emails, just need to see if there's a variance

**Comment by VeNoMouS** [comment] 2019-04-10 11:51
@BarryThrill can you test out dev branch 2.0.3

**Comment by BarryThrill** [comment] 2019-04-10 11:53
Alright! I will do it in around 30-45 minutes from now. Currently in the gym. Need to take out the hate somewhere.

**Comment by BarryThrill** [comment] 2019-04-10 12:17
Alright, so I tried it and I do get errors etc of:^

```
ERROR:root:Error executing Cloudflare IUAM Javascript. Cloudflare may have changed their technique, or there may be a bug in the script.

[14:15:55.955][13] [Get_Product_Info][ReferenceError: ynnDftA is not defined][Retry 8 seconds]

PyJs_Object_24_PyJs_Object_2_ERROR:root:Error executing Cloudflare IUAM Javascript. Cloudflare may have changed their technique, or there may be a bug in the script.

[14:15:56.072][3] [Get_Product_Info]['RuntimeError' object has no attribute 'message'][Retry 8 seconds]
```


Do you want me to send debug version on email?

**Comment by VeNoMouS** [comment] 2019-04-10 12:17
yes please.

**Comment by BarryThrill** [comment] 2019-04-10 12:19
> yes please.

Just sent two from different emails.

**Comment by VeNoMouS** [comment] 2019-04-10 12:20
if you call 

```
import cfscrape
scraper = cfscrape.create_scraper()
scraper.debug = True
scraper.get('https://www.afew-store.com/en/air-jordan-1-retro-high-og-turbo-green-sail-white-ltsmoke-grey/').content
```

Does it work?

**Comment by BarryThrill** [comment] 2019-04-10 12:21
> scraper = cfscrape.create_scraper()
> scraper.debug = True

It seems to be the same thing as I get without .content (Same information as I sent you through email)

**Comment by VeNoMouS** [comment] 2019-04-10 12:22
Is there any error? you didnt send me all the output..

**Comment by VeNoMouS** [comment] 2019-04-10 12:23
also please confirm your using 2.0.3

```
import cfscrape
cfscrape.__version__
```

**Comment by BarryThrill** [comment] 2019-04-10 12:27
> also please confirm your using 2.0.3
> 
> ```
> import cfscrape
> cfscrape.__version__
> ```

Alright, so I can confirm that it is running through 2.0.3 and I will resend now the whole thing. I have no idea that it didn't send the all information.

**Comment by BarryThrill** [comment] 2019-04-10 12:28
However it does seems that it actually works because I do get the content.

**Comment by VeNoMouS** [comment] 2019-04-10 12:29
:) , so errors?

**Comment by VeNoMouS** [comment] 2019-04-10 12:31
re latest email... i don't see any issue there..

**Comment by BarryThrill** [comment] 2019-04-10 12:32
> :) , so errors?

Or wops, It does seems that there is errors. Printing it out here
```

Traceback (most recent call last):
  File "C:/Users/Barry-PC/Desktop/test.py", line 251, in get_product_info
    r = cf_scraper.get(url, proxies=product_info_proxies, timeout=5)
  File "C:\py3.7\lib\site-packages\requests\sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "C:\py3.7\lib\site-packages\cfscrape-2.0.3-py3.7.egg\cfscrape\__init__.py", line 107, in request
    resp = self.solve_cf_challenge(resp, **kwargs)
  File "C:\py3.7\lib\site-packages\cfscrape-2.0.3-py3.7.egg\cfscrape\__init__.py", line 151, in solve_cf_challenge
    params['jschl_answer'] = self.solve_challenge(body, domain)
  File "C:\py3.7\lib\site-packages\cfscrape-2.0.3-py3.7.egg\cfscrape\__init__.py", line 240, in solve_challenge
    result = context.eval(js)
  File "C:\py3.7\lib\site-packages\js2py-0.60-py3.7.egg\js2py\evaljs.py", line 188, in eval
    self.execute(code, use_compilation_plan=use_compilation_plan)
  File "C:\py3.7\lib\site-packages\js2py-0.60-py3.7.egg\js2py\evaljs.py", line 183, in execute
    exec (compiled, self._context)
  File "<EvalJS snippet>", line 4, in <module>
  File "<EvalJS snippet>", line 3, in PyJs_LONG_0_
  File "C:\py3.7\lib\site-packages\js2py-0.60-py3.7.egg\js2py\base.py", line 956, in __call__
    return self.call(self.GlobalObject, args)
  File "C:\py3.7\lib\site-packages\js2py-0.60-py3.7.egg\js2py\base.py", line 1476, in call
    not isinstance(e, NotImplementedError) else 'Not implemented!')
AttributeError: 'RuntimeError' object has no attribute 'message'
```

**Comment by BarryThrill** [comment] 2019-04-10 12:32
```
Exception in thread Thread-12:
Traceback (most recent call last):
  File "C:\py3.7\lib\site-packages\js2py-0.60-py3.7.egg\js2py\base.py", line 1470, in call
    return Js(self.code(*args))
  File "C:\py3.7\lib\site-packages\js2py-0.60-py3.7.egg\js2py\host\jseval.py", line 17, in Eval
    py_code = translate_js(code.to_string().value, '')
  File "C:\py3.7\lib\site-packages\js2py-0.60-py3.7.egg\js2py\translators\translator.py", line 70, in translate_js
    parsed)  # syntax tree to python code
  File "C:\py3.7\lib\site-packages\js2py-0.60-py3.7.egg\js2py\translators\translating_nodes.py", line 121, in trans
    return node(**ele)
  File "C:\py3.7\lib\site-packages\js2py-0.60-py3.7.egg\js2py\translators\translating_nodes.py", line 554, in Program
    code = inline_stack.inject_inlines(code)
  File "C:\py3.7\lib\site-packages\js2py-0.60-py3.7.egg\js2py\translators\translating_nodes.py", line 48, in inject_inlines
    source = inject_before_lval(source, lval, self.reps[lval])
  File "C:\py3.7\lib\site-packages\js2py-0.60-py3.7.egg\js2py\translators\friendly_nodes.py", line 33, in inject_before_lval
    raise RuntimeError('No lval found "%s"' % lval)
RuntimeError: No lval found "PyJs_LONG_10_"
```

**Comment by BarryThrill** [comment] 2019-04-10 12:34
Also I have replaced the name scraper to cf_scraper, Hopefully that wouldn't case any issue?

`cf_scraper = cfscrape.create_scraper()`

**Comment by VeNoMouS** [comment] 2019-04-10 12:36
I need the debug output when those errors occur ....

**Comment by BarryThrill** [comment] 2019-04-10 12:40
> I need the debug output when those errors occur ....

Working on it now! It seems to happen randomly.

**Comment by VeNoMouS** [comment] 2019-04-10 12:40
in your __test.py__ change

```
cf_scraper = cfscrape.create_scraper()
```

to

```
cf_scraper = cfscrape.create_scraper()
cf_scraper = True
```

**Comment by BarryThrill** [comment] 2019-04-10 12:43
Okey sending now, I think I found the error now.

**Comment by BarryThrill** [comment] 2019-04-10 12:45
I forgot to add HTML, Just re-sent HTML aswell.

**Comment by VeNoMouS** [comment] 2019-04-10 12:51
Can you send me your test.py because I replayed that HTML and it decodes fine...

**Comment by BarryThrill** [comment] 2019-04-10 12:52
Alright, Sending in 3 minutes.

**Comment by VeNoMouS** [comment] 2019-04-10 13:09
@BarryThrill I've tried replicating it... but it works every single time...

**Comment by BarryThrill** [comment] 2019-04-10 13:09
I can only think about one thing at this moment. I tried to use threading where I apply etc 10 different links at the same time. It seems to happen if you run all the sites at the same time. But I doubt that it shouldn't matter since each thread is running for its own?

**Comment by BarryThrill** [comment] 2019-04-10 13:09
Let me send you another testing, maybe it will come. Hold up few minutes!

**Comment by BarryThrill** [comment] 2019-04-10 13:13
Alright, I think I made a perfect test script now for testing! Sending it over now.

**Comment by VeNoMouS** [comment] 2019-04-10 13:14
Personally... if your going to the same site...

why cf_solve on each one.. just setup a session and solve that .. then pass the session or the cookie to your threads for the request...

seems so silly to do it any other way.

**Comment by BarryThrill** [comment] 2019-04-10 13:17
> Personally... if your going to the same site...
> 
> why cf_solve on each one.. just setup a session and solve that .. then pass the session or the cookie to your threads for the request...
> 
> seems so silly to do it any other way.

I have not thought about it, I thought using proxies might could giving trouble/error using session. I just sent and I believe you might be able to run it

**Comment by VeNoMouS** [comment] 2019-04-10 13:18
You need to learn threading better, you have no queue control let alone child control, too many urls in your list, and you would fork bomb yourself due to threads.

**Comment by BarryThrill** [comment] 2019-04-10 13:20
> You need to learn threading better, you have no queue control let alone child control, too many urls in your list, and you would fork bomb yourself due to threads.

Yeah probably, I mean it always worked for me pretty well but you might have been right. I never had anyone that was willing to check my code and letting me know these stuff at all. I could explain it better but I am not sure if it is fine to explain it here of what my achievement for the script I am trying to do 😃

**Comment by VeNoMouS** [comment] 2019-04-10 13:25
before you main, I would call one of the sites that triggers and do... maybe

```
cookies = cf_scraper.get_tokens('https://www.afew-store.com/en/air-jordan-1-retro-high-og-turbo-green-sail-white-ltsmoke-grey/')[0]
```

then I would pass cookies to the child threads , and on the get send the cookies... that way it wouldnt have to code solve on each request...

just one of many ways.

**Comment by VeNoMouS** [comment] 2019-04-10 13:28
anyway its 0130... im outtie for the night.

**Comment by BarryThrill** [comment] 2019-04-10 13:29
Appreciate all the help for today! Do you recommend to run the 2.0.3 or did you push update for master?

I will probably need to re-code the whole thing now but I guess that's what coding is all about. I might need more tip such as headers etc etc. but I could talk to you about it another day whenever you have time!

**Comment by VeNoMouS** [comment] 2019-04-10 13:30
I pushed it for master... If i find some time tomorrow i'll send you through how I do threading with queue control and child fork limitation...

**Comment by BarryThrill** [comment] 2019-04-10 13:31
> I pushed it for master... If i find some time tomorrow i'll send you through how I do threading with queue control and child fork limitation...

Thats awesome! I will send you an email but you could read it tomorrow! I apprecaite for everything honestly!

**Comment by VeNoMouS** [comment] 2019-04-10 13:32
np mate :)

anyway, good night :)

**Comment by VeNoMouS** [comment] 2019-04-10 13:33
I'm going to close this for now, if you have an issue we can re-open it.

**Closed by VeNoMouS** 2019-04-10 13:33 UTC
Labels: question
